package Latte.Absyn; // Java Package generated by the BNF Converter.

public class Arg {
  public final Type type_;
  public final String ident_;

  public Arg(Type p1, String p2) { type_ = p1; ident_ = p2; }

  public <R,A> R accept(Latte.Absyn.Arg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.Arg) {
      Latte.Absyn.Arg x = (Latte.Absyn.Arg)o;
      return this.type_.equals(x.type_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.ident_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(Latte.Absyn.Arg p, A arg);

  }

}
