package Latte.Absyn; // Java Package generated by the BNF Converter.

public class Program {
  public final ListTopDef listtopdef_;

  public Program(ListTopDef p1) { listtopdef_ = p1; }

  public <R,A> R accept(Latte.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.Program) {
      Latte.Absyn.Program x = (Latte.Absyn.Program)o;
      return this.listtopdef_.equals(x.listtopdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtopdef_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(Latte.Absyn.Program p, A arg);

  }

}
