package Latte.Absyn; // Java Package generated by the BNF Converter.

public class SEmpty extends Stmt {

  public SEmpty() { }

  public <R,A> R accept(Latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.SEmpty) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
