package Latte.Absyn; // Java Package generated by the BNF Converter.

public class SRet extends Stmt {
  public final Expr expr_;

  public SRet(Expr p1) { expr_ = p1; }

  public <R,A> R accept(Latte.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof Latte.Absyn.SRet) {
      Latte.Absyn.SRet x = (Latte.Absyn.SRet)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
