package Latte.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stmt implements java.io.Serializable {
  public abstract <R,A> R accept(Stmt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(Latte.Absyn.SEmpty p, A arg);
    public R visit(Latte.Absyn.SBStmt p, A arg);
    public R visit(Latte.Absyn.SDecl p, A arg);
    public R visit(Latte.Absyn.SAss p, A arg);
    public R visit(Latte.Absyn.SIncr p, A arg);
    public R visit(Latte.Absyn.SDecr p, A arg);
    public R visit(Latte.Absyn.SRet p, A arg);
    public R visit(Latte.Absyn.SVRet p, A arg);
    public R visit(Latte.Absyn.SCond p, A arg);
    public R visit(Latte.Absyn.SCondElse p, A arg);
    public R visit(Latte.Absyn.SWhile p, A arg);
    public R visit(Latte.Absyn.SExp p, A arg);

  }

}
